title: Dongyoung Study Log
description: Personal Study Blog

repository: Muroi6666/Muroi6666.github.io

remote_theme: marella/jekyll-theme-documentation

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge

exclude:
  - lang_chain/langchain.py
  - lang_chain/requirements.txt
  - lang_chain/data
  - lang_chain/data-20260528T021220Z-3-001.zip
  - lang_chain/.env
  - lang_chain/.env.*
